# Application Configuration
app:
  name: "Weather News Aggregator"
  version: "1.0.0"
  enableMockMode: true  # Set to false for production with real API keys
  
# HTTP Configuration
http:
  listener:
    host: "0.0.0.0"
    port: 8081
  
# External API Configurations
apis:
  openweather:
    host: "api.openweathermap.org"
    port: 443
    protocol: "HTTPS"
    basePath: "/data/2.5"
    apiKey: "${secure::openweather.api.key}"
    timeout: 30000
    
  newsapi:
    host: "newsapi.org"
    port: 443  
    protocol: "HTTPS"
    basePath: "/v2"
    apiKey: "${secure::newsapi.key}"
    timeout: 30000
    
  jsonplaceholder:
    host: "jsonplaceholder.typicode.com"
    port: 443
    protocol: "HTTPS" 
    basePath: ""
    timeout: 15000

# Batch Processing Configuration
batch:
  maxConcurrency: 5
  timeout: 60000
  
# Cache Configuration  
cache:
  weather:
    ttl: 600  # 10 minutes
  news:
    ttl: 1800  # 30 minutes
    
# Logging Configuration
logging:
  level: INFO
  pattern: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"